export const CATEGORIES = [
  'RESTAURANT',
  'CAFE',
  'HOTEL',
  'SHOPPING',
  'TRANSPORT',
  'HOSPITAL',
  'PHARMACY',
  'PARK',
  'EDUCATION',
  'ENTERTAINMENT',
  'SPORT',
  'GOVERNMENT',
  'RELIGIOUS',
  'TOURISM',
  'SUPERMARKET',
  'BANK',
  'POST_OFFICE',
  'MUSEUM',
  'LIBRARY',
  'BEACH',
  'PUBLIC_TOILET',
  'OTHER',
] as const

export const ACCESSIBILITY_FEATURES = [
  'Ramp',
  'Elevator',
  'Accessible Toilet',
  'Accessible Parking',
  'Wide Doorways',
  'Lowered Counter',
  'Braille Signage',
  'Hearing Loop',
  'Automatic Doors',
  'Step-Free Entrance',
  'Level Flooring',
  'Accessible Seating Area',
  'Wheelchair Turning Space',
  'Accessible Changing Room',
  'Tactile Paving',
  'Visual Display Screens',
  'Staff Assistance Available',
  'Accessible Ticket Machine',
  'Accessible Lift Buttons',
  'Accessible Emergency Exit',
  'Accessible Pathways',
  'Reserved Wheelchair Spaces',
  'Audio Announcements',
  'Accessible Playground Equipment',
  'Accessible Picnic Tables',
  'Accessible Viewing Platform',
  'Low Gradient Slope',
  'Handrails',
  'Accessible Shower',
  'Pool Hoist',
] as const

export const MEDIA_TYPES = ['VIDEO', 'AUDIO'] as const